pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'jenkins/make.sh' 
                //archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true //
            }
        }
    }
}
