pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                /* `make check` returns non-zero on test failures,
                * using `true` to allow the Pipeline to continue nonetheless
                */
                
		sh 'jenkins/make.sh check || true'  // 1 //
                echo 'Building ....'
		echo '특정 명령에 의하여 종료 코드가 성공일 시 Build 파일을 캡처 하고 Jenkins 컨트롤러에 저장'
            }
        }
	stage('Test'){
	    steps {
	          echo 'Testing..'
		  echo 'Jenkins Test Plugin을 사용하여 테스트 기록, 보고 및 시각화'

 	    }
	}
	stage('Deploy') {
	    steps {
		echo 'Deploying..'
		echo '앞선 Build 및 Test가 성공적으로 실행 될 시 실행되며'
		echo 'currentBuild.result 구문을 사용하여 Test stage에서 실패가 있는지 확인 할 수 있습니다'
	    }
	}
    }
}
